### ISSUE TITLE
翻譯進度

### ISSUE THREAD

**Issue by chentsulin** [chentsulin/redux#1]
- [x] 1.Read Me
- [x] 2. 介紹
  - [x] 2.1 動機
  - [x] 2.2 三大原則
  - [x] 2.3 先前技術
  - [x] 2.4 生態系
  - [x] 2.5 範例
- [x] 3. 基礎
  - [x] 3.1 Actions
  - [x] 3.2 Reducers
  - [x] 3.3 Store
  - [x] 3.4 資料流 
  - [x] 3.5 搭配 React 運用 
  - [x] 3.6 範例：Todo 清單 
- [x] 4. 進階
  - [x] 4.1 Middleware
  - [x] 4.2 Async Actions
  - [x] 4.3 非同步資料流
  - [x] 4.4 搭配 React Router 運用 (wait for upstream)
  - [x] 4.5 範例：Reddit API
  - [x] 4.6 接下來 (wait for upstream)
- [x] 5. Recipes
  - [x] 5.1 遷移到 Redux
  - [x] 5.2 減少 Boilerplate
  - [x] 5.3 伺服器 Render
  - [x] 5.4 撰寫測試
  - [x] 5.5 計算衍生資料
  - [x] 5.6 實作 Undo 歷史
  - [x] 5.7 隔離 Redux 子應用程式
- [x] 6. 疑難排解
- [x] 7. 術語表
- [x] 8. API 參考
  - [x] 8.1 createStore
  - [x] 8.2 Store
  - [x] 8.3 combineReducers
  - [x] 8.4 applyMiddleware
  - [x] 8.5 bindActionCreators
  - [x] 8.6 compose
- [x] 9. 贊助者

**Comment by chentsulin** [comment]
Done!!!

**Comment by neighborhood999** [comment]
@chentsulin 辛苦了！:+1:

**Comment by MnHung** [comment]
讚喔讚喔
