### ISSUE TITLE
gitbook 網頁 issue

### ISSUE THREAD

**Issue by chentsulin** [chentsulin/redux#16]
- [x] 速度慢
- [x] 子頁面的連結壞了

**Comment by neighborhood999** [comment]
@chentsulin 時好時壞耶，有時會跳 404 Not Found，不然就是會像這樣：
![](http://i.imgur.com/34wcBRW.png)

**Comment by chentsulin** [comment]
https://github.com/camsong/redux-in-chinese 也有 UI blocking 的問題
不過他們沒有 routing 問題

**Comment by chentsulin** [comment]
![2016-03-24 1 57 18](https://cloud.githubusercontent.com/assets/3382565/14009601/751b86b0-f1c8-11e5-95e2-c6513aac6423.png)

**Comment by chentsulin** [comment]
@appleboy 有遇過這種狀況嗎？這算是 gitbook 的問題？

**Comment by appleboy** [comment]
@chentsulin 這部分我沒遇過，感覺好像是 gitbook 問題

**Comment by appleboy** [comment]
會很常發生嗎？

**Comment by lenchen1112** [comment]
用 webpagetest 用(5/1 Mbps cable)開9次頁面的平均結果：
http://www.webpagetest.org/result/160327_JD_CE5/9/details/

DOM interactive 大概落在 1.9s 左右，document complete 大概落在 2.3s 左右，個人感覺是 gitbook 當時不太穩定 XD

**Comment by chentsulin** [comment]
沒什麼時間認真去看 gitbook 連結什麼問題...

所以我先 workaround 了：https://github.com/chentsulin/redux/blob/new-doc-zh-tw/build/fix-wrong-path.js

可以看看是不是沒問題了
